name: CI Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
        
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Verify Flutter Installation
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test

      - name: Build Flutter Windows app
        run: flutter build windows

      - name: Move build output to D drive
        run: |
          set targetPath=D:\MyApps\FlutterApp
          if exist %targetPath% (
            rmdir /S /Q %targetPath%
          )
          mkdir %targetPath%
          move build\windows\x64\runner\Release\* D:\flutterapp

      # - name: Upload Build Artifacts
      #   if: success()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: windows-app
      #     path: build/windows/runner/Release/