name: CI Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main


jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter build windows

      - name: Move build output to D drive
        run: |
          mkdir D:\output
          move build\windows\runner\Release\* D:\flutterapp

      # - name: Upload Build Artifacts
      #   if: success()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: windows-app
      #     path: build/windows/runner/Release/