name: CI Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
        
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test

      - name: Run tests
        run: flutter build windows

      - name: Move build output to D drive
        run: |
          mkdir D:\output
          move build\windows\runner\Release\* D:\flutterapp

      # - name: Upload Build Artifacts
      #   if: success()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: windows-app
      #     path: build/windows/runner/Release/